name: React App CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  S3_BUCKET_NAME: be-0-name

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ secrets.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ secrets.NODE_VERSION }}
        
    - name: Cache node modules
      uses: actions/cache@v2
      id: cache
      with:
        path: node_modules
        key: npm-packages-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install

    - name: Run the tests and generate coverage report
      run: npm test -- --coverage

    - name: Build
      run: npm run build
      
    - name: Make zip file
      run: zip -r ./react-app-deploy.zip .
      shell: bash
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./react-app-deploy.zip s3://$S3_BUCKET_NAME/react-app-deploy.zip

    - name: Deploy
      run: >
        aws deploy create-deployment --application-name golong-deploy
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name golong-deploy-group
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=react-app-deploy.zip
