name: S3 deploy with cloud front
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  CI: false
  REACT_APP_BUCKET_NAME: ${{ secrets.REACT_APP_BUCKET_NAME }}
  REACT_APP_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  REACT_APP_ACCESS: ${{ secrets.AWS_ACCESS_KEY_ID }}
  REACT_APP_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REACT_APP_PORTONE_IDENT_CODE: ${{ secrets.REACT_APP_PORTONE_IDENT_CODE }}
  REACT_APP_PORTONE_API_KEY: ${{ secrets.REACT_APP_PORTONE_API_KEY }}
  REACT_APP_PORTONE_API_SECRET_KEY: ${{ secrets.REACT_APP_PORTONE_API_SECRET_KEY }}
  REACT_APP_KAKAO_API_KEY: ${{ secrets.REACT_APP_KAKAO_API_KEY }}
  REACT_APP_NAVER_CLIENT_ID: ${{ secrets.REACT_APP_NAVER_CLIENT_ID }}
  REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
  REACT_APP_API_ENDPOINT: ${{ secrets.REACT_APP_API_ENDPOINT }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ secrets.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ secrets.NODE_VERSION }}
        
    - name: Cache node modules
      uses: actions/cache@v2
      id: cache
      with:
        path: node_modules
        key: npm-packages-${{ hashFiles('**/package-lock.json') }}
        
    - name: Generate Environment Variables File for Production
      run: |
        echo "REACT_APP_BUCKET_NAME=$REACT_APP_BUCKET_NAME" >> .env
        echo "REACT_APP_REGION=$REACT_APP_REGION" >> .env
        echo "REACT_APP_ACCESS=$REACT_APP_ACCESS" >> .env
        echo "REACT_APP_SECRET=$REACT_APP_SECRET" >> .env
        echo "REACT_APP_PORTONE_IDENT_CODE=$REACT_APP_PORTONE_IDENT_CODE" >> .env
        echo "REACT_APP_PORTONE_API_KEY=$REACT_APP_PORTONE_API_KEY" >> .env
        echo "REACT_APP_PORTONE_API_SECRET_KEY=$REACT_APP_PORTONE_API_SECRET_KEY" >> .env
        echo "REACT_APP_KAKAO_API_KEY=$REACT_APP_KAKAO_API_KEY" >> .env
        echo "REACT_APP_NAVER_CLIENT_ID=$REACT_APP_NAVER_CLIENT_ID" >> .env
        echo "REACT_APP_GOOGLE_CLIENT_ID=$REACT_APP_GOOGLE_CLIENT_ID" >> .env
        echo "REACT_APP_API_ENDPOINT=$REACT_APP_API_ENDPOINT" >> .env

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install

    - name: Build
      run: npm run build
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Deploy
      run : aws s3 cp --recursive --region ap-northeast-2 build s3://golong-s3-cloudfront-bucket
